#+title: colporter
#+author: Ruben Philipp
#+date: 2023-07-09
#+startup: showall 

/colporter/ is a static-site generator written in Common Lisp.
Its HTML generation is able to take advantage of [[https://github.com/ruricolist/spinneret][Spinneret]] (cf.
~tests/tests.lisp~ and ~examples/~).

Tested with SBCL.

* Usage notes

A tutorial is coming up soon. For now, refer to ~examples/~ and the
code documentation, available in ~doc/~ or
[[http://code.rubenphilipp.com/colporter]].

** Examples

The ~examples/~ directory contains examples and a template to get started.

A real-world example is [[http://rubenphilipp.com]] which is created and maintained
using /colporter/.



* Project Structure

- ~/src~. Contains the source code of the project.
- ~/doc~. Contains a documentation generated via [[https://github.com/gumpu/ROBODoc][ROBODoc]].
- ~/tests~. Regression tests via [[https://github.com/lispci/fiveam][fiveam]].
- ~/examples~. Example files for demonstration purposes.


* Requirements

** Lisp-wise

- [[https://www.sbcl.org][SBCL]] (or comparable)
  - currently, /colporter/ is only tested on MacOS with SBCL
- [[https://asdf.common-lisp.dev][ASDF]]

** Server

- Apache 2 (for htaccess support, e.g. for custom error pages and mod_rewrite)


* Nota Bene

As of August 2023, it is necessary to configure the web-server to redirect page
requests to a file matching the /output-suffix/ (e.g. "html") given to
~make-colporter~, as the links generated by /colporter/ purposefully do not take
into account the format used to eventually build the site into account.  Anyway,
this could be easily done (on an Apache server) by adding an ~.htaccess~ file to
the root of the ~content/~ (or similarly named) directory of the site. The
~examples/~ explicate such approaches.


#+begin_comment
$$ Last modified:  21:35:10 Sat Jul 20 2024 CEST
#+end_comment
